### ISSUE TITLE
Исправить ошибки в CODEOWNERS

### ISSUE THREAD

**Issue by StarHamster** [doka-guide/.github#10]

**Comment by furtivite** [comment]
@StarHamster спасибо, что обратили внимание, но было бы более информативно, если бы у issue появилось описание.

**Comment by StarHamster** [comment]
@furtivite, ох, я просто не придумал, что можно написать... 🥲

**Comment by furtivite** [comment]
@StarHamster и всё равно, круто, что обратили внимание) Приходите и в другие репозитории, мы будем рады)
